# Generated by Django 5.0.6 on 2025-02-21 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app_api_customer.customer')),
            ],
        ),
    ]
