# Generated by Django 5.0.6 on 2025-02-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_customer', '0002_remove_product_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_api_customer.customer'),
            preserve_default=False,
        ),
    ]
