# Generated by Django 5.0.6 on 2025-02-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_customer', '0003_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='invoice',
        ),
    ]
