# Generated by Django 5.0.6 on 2025-02-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_customer', '0006_rename_product_invoiceproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
